//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esendex.Voice.Sdk.Esendex.VoiceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampaignSettings", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
        "aging.PublicApi.DataContracts")]
    [System.SerializableAttribute()]
    public partial class CampaignSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AnswerphoneOptionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid BlacklistOptionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CallCascadeOptionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CallRetryOptionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CallerLineIdentityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConcurrentCallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndingAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAllowedToRollOverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinutesBetweenRetryAttemptsWhenEngagedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinutesBetweenRetryAttemptsWhenNoAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfAttemptsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShouldLeaveAnswerphoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartingAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AnswerphoneOptionId {
            get {
                return this.AnswerphoneOptionIdField;
            }
            set {
                if ((this.AnswerphoneOptionIdField.Equals(value) != true)) {
                    this.AnswerphoneOptionIdField = value;
                    this.RaisePropertyChanged("AnswerphoneOptionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BlacklistOptionId {
            get {
                return this.BlacklistOptionIdField;
            }
            set {
                if ((this.BlacklistOptionIdField.Equals(value) != true)) {
                    this.BlacklistOptionIdField = value;
                    this.RaisePropertyChanged("BlacklistOptionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CallCascadeOptionId {
            get {
                return this.CallCascadeOptionIdField;
            }
            set {
                if ((this.CallCascadeOptionIdField.Equals(value) != true)) {
                    this.CallCascadeOptionIdField = value;
                    this.RaisePropertyChanged("CallCascadeOptionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CallRetryOptionId {
            get {
                return this.CallRetryOptionIdField;
            }
            set {
                if ((this.CallRetryOptionIdField.Equals(value) != true)) {
                    this.CallRetryOptionIdField = value;
                    this.RaisePropertyChanged("CallRetryOptionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CallerLineIdentityId {
            get {
                return this.CallerLineIdentityIdField;
            }
            set {
                if ((this.CallerLineIdentityIdField.Equals(value) != true)) {
                    this.CallerLineIdentityIdField = value;
                    this.RaisePropertyChanged("CallerLineIdentityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConcurrentCalls {
            get {
                return this.ConcurrentCallsField;
            }
            set {
                if ((this.ConcurrentCallsField.Equals(value) != true)) {
                    this.ConcurrentCallsField = value;
                    this.RaisePropertyChanged("ConcurrentCalls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndingAt {
            get {
                return this.EndingAtField;
            }
            set {
                if ((this.EndingAtField.Equals(value) != true)) {
                    this.EndingAtField = value;
                    this.RaisePropertyChanged("EndingAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAllowedToRollOver {
            get {
                return this.IsAllowedToRollOverField;
            }
            set {
                if ((this.IsAllowedToRollOverField.Equals(value) != true)) {
                    this.IsAllowedToRollOverField = value;
                    this.RaisePropertyChanged("IsAllowedToRollOver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinutesBetweenRetryAttemptsWhenEngaged {
            get {
                return this.MinutesBetweenRetryAttemptsWhenEngagedField;
            }
            set {
                if ((this.MinutesBetweenRetryAttemptsWhenEngagedField.Equals(value) != true)) {
                    this.MinutesBetweenRetryAttemptsWhenEngagedField = value;
                    this.RaisePropertyChanged("MinutesBetweenRetryAttemptsWhenEngaged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinutesBetweenRetryAttemptsWhenNoAnswer {
            get {
                return this.MinutesBetweenRetryAttemptsWhenNoAnswerField;
            }
            set {
                if ((this.MinutesBetweenRetryAttemptsWhenNoAnswerField.Equals(value) != true)) {
                    this.MinutesBetweenRetryAttemptsWhenNoAnswerField = value;
                    this.RaisePropertyChanged("MinutesBetweenRetryAttemptsWhenNoAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfAttempts {
            get {
                return this.NumberOfAttemptsField;
            }
            set {
                if ((this.NumberOfAttemptsField.Equals(value) != true)) {
                    this.NumberOfAttemptsField = value;
                    this.RaisePropertyChanged("NumberOfAttempts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShouldLeaveAnswerphone {
            get {
                return this.ShouldLeaveAnswerphoneField;
            }
            set {
                if ((this.ShouldLeaveAnswerphoneField.Equals(value) != true)) {
                    this.ShouldLeaveAnswerphoneField = value;
                    this.RaisePropertyChanged("ShouldLeaveAnswerphone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartingAt {
            get {
                return this.StartingAtField;
            }
            set {
                if ((this.StartingAtField.Equals(value) != true)) {
                    this.StartingAtField = value;
                    this.RaisePropertyChanged("StartingAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessDeniedFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
        "aging.PublicApi.FaultExceptions")]
    [System.SerializableAttribute()]
    public partial class AccessDeniedFaultException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallflowNotFoundFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
        "aging.PublicApi.FaultExceptions")]
    [System.SerializableAttribute()]
    public partial class CallflowNotFoundFaultException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampaignDoesNotExistFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
        "aging.PublicApi.FaultExceptions")]
    [System.SerializableAttribute()]
    public partial class CampaignDoesNotExistFaultException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CampaignIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CampaignId {
            get {
                return this.CampaignIdField;
            }
            set {
                if ((this.CampaignIdField.Equals(value) != true)) {
                    this.CampaignIdField = value;
                    this.RaisePropertyChanged("CampaignId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidCampaignSettingFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
        "aging.PublicApi.FaultExceptions")]
    [System.SerializableAttribute()]
    public partial class InvalidCampaignSettingFaultException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Esendex.Voice.Sdk.Esendex.VoiceService.AbstractCampaignSettingValidationError[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Esendex.Voice.Sdk.Esendex.VoiceService.AbstractCampaignSettingValidationError[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractCampaignSettingValidationError", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
        "aging.PublicApi.Validation.ValidationErrors")]
    [System.SerializableAttribute()]
    public partial class AbstractCampaignSettingValidationError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SettingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidationMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettingName {
            get {
                return this.SettingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SettingNameField, value) != true)) {
                    this.SettingNameField = value;
                    this.RaisePropertyChanged("SettingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidationMessage {
            get {
                return this.ValidationMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationMessageField, value) != true)) {
                    this.ValidationMessageField = value;
                    this.RaisePropertyChanged("ValidationMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
        "aging.PublicApi.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ContactIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Esendex.Voice.Sdk.Esendex.VoiceService.ContactNumber[] NumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Esendex.Voice.Sdk.Esendex.VoiceService.ContactVariable[] VariablesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ContactId {
            get {
                return this.ContactIdField;
            }
            set {
                if ((this.ContactIdField.Equals(value) != true)) {
                    this.ContactIdField = value;
                    this.RaisePropertyChanged("ContactId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Esendex.Voice.Sdk.Esendex.VoiceService.ContactNumber[] Numbers {
            get {
                return this.NumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.NumbersField, value) != true)) {
                    this.NumbersField = value;
                    this.RaisePropertyChanged("Numbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Esendex.Voice.Sdk.Esendex.VoiceService.ContactVariable[] Variables {
            get {
                return this.VariablesField;
            }
            set {
                if ((object.ReferenceEquals(this.VariablesField, value) != true)) {
                    this.VariablesField = value;
                    this.RaisePropertyChanged("Variables");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactNumber", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
        "aging.PublicApi.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ContactNumber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderIndex {
            get {
                return this.OrderIndexField;
            }
            set {
                if ((this.OrderIndexField.Equals(value) != true)) {
                    this.OrderIndexField = value;
                    this.RaisePropertyChanged("OrderIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactVariable", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
        "aging.PublicApi.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ContactVariable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoPhoneNumbersForContactFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
        "aging.PublicApi.FaultExceptions")]
    [System.SerializableAttribute()]
    public partial class NoPhoneNumbersForContactFaultException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Callflow", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
        "aging.PublicApi.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Callflow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Esendex.Voice.Sdk.Esendex.VoiceService.CallerLineIdentity[] CallerLineIdentitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CallflowIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Esendex.Voice.Sdk.Esendex.VoiceService.TransferNumber[] TransferNumbersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Esendex.Voice.Sdk.Esendex.VoiceService.CallerLineIdentity[] CallerLineIdentities {
            get {
                return this.CallerLineIdentitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.CallerLineIdentitiesField, value) != true)) {
                    this.CallerLineIdentitiesField = value;
                    this.RaisePropertyChanged("CallerLineIdentities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CallflowId {
            get {
                return this.CallflowIdField;
            }
            set {
                if ((this.CallflowIdField.Equals(value) != true)) {
                    this.CallflowIdField = value;
                    this.RaisePropertyChanged("CallflowId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Esendex.Voice.Sdk.Esendex.VoiceService.TransferNumber[] TransferNumbers {
            get {
                return this.TransferNumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferNumbersField, value) != true)) {
                    this.TransferNumbersField = value;
                    this.RaisePropertyChanged("TransferNumbers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallerLineIdentity", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
        "aging.PublicApi.DataContracts")]
    [System.SerializableAttribute()]
    public partial class CallerLineIdentity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CallerLineIdentityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentityTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CallerLineIdentityId {
            get {
                return this.CallerLineIdentityIdField;
            }
            set {
                if ((this.CallerLineIdentityIdField.Equals(value) != true)) {
                    this.CallerLineIdentityIdField = value;
                    this.RaisePropertyChanged("CallerLineIdentityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentityText {
            get {
                return this.IdentityTextField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentityTextField, value) != true)) {
                    this.IdentityTextField = value;
                    this.RaisePropertyChanged("IdentityText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferNumber", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
        "aging.PublicApi.DataContracts")]
    [System.SerializableAttribute()]
    public partial class TransferNumber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderPositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderPosition {
            get {
                return this.OrderPositionField;
            }
            set {
                if ((this.OrderPositionField.Equals(value) != true)) {
                    this.OrderPositionField = value;
                    this.RaisePropertyChanged("OrderPosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Esendex.VoiceService.ICollstreamVoiceService")]
    public interface ICollstreamVoiceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollstreamVoiceService/CreateCampaign", ReplyAction="http://tempuri.org/ICollstreamVoiceService/CreateCampaignResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Esendex.Voice.Sdk.Esendex.VoiceService.AccessDeniedFaultException), Action="http://tempuri.org/ICollstreamVoiceService/CreateCampaignAccessDeniedFaultExcepti" +
            "onFault", Name="AccessDeniedFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
            "aging.PublicApi.FaultExceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Esendex.Voice.Sdk.Esendex.VoiceService.CallflowNotFoundFaultException), Action="http://tempuri.org/ICollstreamVoiceService/CreateCampaignCallflowNotFoundFaultExc" +
            "eptionFault", Name="CallflowNotFoundFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
            "aging.PublicApi.FaultExceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Esendex.Voice.Sdk.Esendex.VoiceService.CampaignDoesNotExistFaultException), Action="http://tempuri.org/ICollstreamVoiceService/CreateCampaignCampaignDoesNotExistFaul" +
            "tExceptionFault", Name="CampaignDoesNotExistFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
            "aging.PublicApi.FaultExceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Esendex.Voice.Sdk.Esendex.VoiceService.InvalidCampaignSettingFaultException), Action="http://tempuri.org/ICollstreamVoiceService/CreateCampaignInvalidCampaignSettingFa" +
            "ultExceptionFault", Name="InvalidCampaignSettingFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
            "aging.PublicApi.FaultExceptions")]
        System.Guid CreateCampaign(string title, System.Guid callflowId, Esendex.Voice.Sdk.Esendex.VoiceService.CampaignSettings settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollstreamVoiceService/CreateCampaign", ReplyAction="http://tempuri.org/ICollstreamVoiceService/CreateCampaignResponse")]
        System.Threading.Tasks.Task<System.Guid> CreateCampaignAsync(string title, System.Guid callflowId, Esendex.Voice.Sdk.Esendex.VoiceService.CampaignSettings settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollstreamVoiceService/AddContact", ReplyAction="http://tempuri.org/ICollstreamVoiceService/AddContactResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Esendex.Voice.Sdk.Esendex.VoiceService.CampaignDoesNotExistFaultException), Action="http://tempuri.org/ICollstreamVoiceService/AddContactCampaignDoesNotExistFaultExc" +
            "eptionFault", Name="CampaignDoesNotExistFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
            "aging.PublicApi.FaultExceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Esendex.Voice.Sdk.Esendex.VoiceService.AccessDeniedFaultException), Action="http://tempuri.org/ICollstreamVoiceService/AddContactAccessDeniedFaultExceptionFa" +
            "ult", Name="AccessDeniedFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
            "aging.PublicApi.FaultExceptions")]
        System.Guid AddContact(System.Guid campaignId, Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollstreamVoiceService/AddContact", ReplyAction="http://tempuri.org/ICollstreamVoiceService/AddContactResponse")]
        System.Threading.Tasks.Task<System.Guid> AddContactAsync(System.Guid campaignId, Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollstreamVoiceService/ScheduleContact", ReplyAction="http://tempuri.org/ICollstreamVoiceService/ScheduleContactResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Esendex.Voice.Sdk.Esendex.VoiceService.AccessDeniedFaultException), Action="http://tempuri.org/ICollstreamVoiceService/ScheduleContactAccessDeniedFaultExcept" +
            "ionFault", Name="AccessDeniedFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
            "aging.PublicApi.FaultExceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Esendex.Voice.Sdk.Esendex.VoiceService.CampaignDoesNotExistFaultException), Action="http://tempuri.org/ICollstreamVoiceService/ScheduleContactCampaignDoesNotExistFau" +
            "ltExceptionFault", Name="CampaignDoesNotExistFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
            "aging.PublicApi.FaultExceptions")]
        System.Guid ScheduleContact(System.Guid campaignId, Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollstreamVoiceService/ScheduleContact", ReplyAction="http://tempuri.org/ICollstreamVoiceService/ScheduleContactResponse")]
        System.Threading.Tasks.Task<System.Guid> ScheduleContactAsync(System.Guid campaignId, Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollstreamVoiceService/MakeCall", ReplyAction="http://tempuri.org/ICollstreamVoiceService/MakeCallResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Esendex.Voice.Sdk.Esendex.VoiceService.NoPhoneNumbersForContactFaultException), Action="http://tempuri.org/ICollstreamVoiceService/MakeCallNoPhoneNumbersForContactFaultE" +
            "xceptionFault", Name="NoPhoneNumbersForContactFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
            "aging.PublicApi.FaultExceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Esendex.Voice.Sdk.Esendex.VoiceService.CallflowNotFoundFaultException), Action="http://tempuri.org/ICollstreamVoiceService/MakeCallCallflowNotFoundFaultException" +
            "Fault", Name="CallflowNotFoundFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
            "aging.PublicApi.FaultExceptions")]
        System.Guid MakeCall(Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollstreamVoiceService/MakeCall", ReplyAction="http://tempuri.org/ICollstreamVoiceService/MakeCallResponse")]
        System.Threading.Tasks.Task<System.Guid> MakeCallAsync(Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollstreamVoiceService/ScheduleCall", ReplyAction="http://tempuri.org/ICollstreamVoiceService/ScheduleCallResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Esendex.Voice.Sdk.Esendex.VoiceService.CallflowNotFoundFaultException), Action="http://tempuri.org/ICollstreamVoiceService/ScheduleCallCallflowNotFoundFaultExcep" +
            "tionFault", Name="CallflowNotFoundFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
            "aging.PublicApi.FaultExceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Esendex.Voice.Sdk.Esendex.VoiceService.NoPhoneNumbersForContactFaultException), Action="http://tempuri.org/ICollstreamVoiceService/ScheduleCallNoPhoneNumbersForContactFa" +
            "ultExceptionFault", Name="NoPhoneNumbersForContactFaultException", Namespace="http://schemas.datacontract.org/2004/07/Collstream.Services.Application.VoiceMess" +
            "aging.PublicApi.FaultExceptions")]
        System.Guid ScheduleCall(Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact, System.DateTime whenToMakeCall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollstreamVoiceService/ScheduleCall", ReplyAction="http://tempuri.org/ICollstreamVoiceService/ScheduleCallResponse")]
        System.Threading.Tasks.Task<System.Guid> ScheduleCallAsync(Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact, System.DateTime whenToMakeCall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollstreamVoiceService/GetCallflows", ReplyAction="http://tempuri.org/ICollstreamVoiceService/GetCallflowsResponse")]
        Esendex.Voice.Sdk.Esendex.VoiceService.Callflow[] GetCallflows();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollstreamVoiceService/GetCallflows", ReplyAction="http://tempuri.org/ICollstreamVoiceService/GetCallflowsResponse")]
        System.Threading.Tasks.Task<Esendex.Voice.Sdk.Esendex.VoiceService.Callflow[]> GetCallflowsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICollstreamVoiceServiceChannel : Esendex.Voice.Sdk.Esendex.VoiceService.ICollstreamVoiceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CollstreamVoiceServiceClient : System.ServiceModel.ClientBase<Esendex.Voice.Sdk.Esendex.VoiceService.ICollstreamVoiceService>, Esendex.Voice.Sdk.Esendex.VoiceService.ICollstreamVoiceService {
        
        public CollstreamVoiceServiceClient() {
        }
        
        public CollstreamVoiceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CollstreamVoiceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollstreamVoiceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollstreamVoiceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid CreateCampaign(string title, System.Guid callflowId, Esendex.Voice.Sdk.Esendex.VoiceService.CampaignSettings settings) {
            return base.Channel.CreateCampaign(title, callflowId, settings);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateCampaignAsync(string title, System.Guid callflowId, Esendex.Voice.Sdk.Esendex.VoiceService.CampaignSettings settings) {
            return base.Channel.CreateCampaignAsync(title, callflowId, settings);
        }
        
        public System.Guid AddContact(System.Guid campaignId, Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact) {
            return base.Channel.AddContact(campaignId, contact);
        }
        
        public System.Threading.Tasks.Task<System.Guid> AddContactAsync(System.Guid campaignId, Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact) {
            return base.Channel.AddContactAsync(campaignId, contact);
        }
        
        public System.Guid ScheduleContact(System.Guid campaignId, Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact, System.DateTime dateTime) {
            return base.Channel.ScheduleContact(campaignId, contact, dateTime);
        }
        
        public System.Threading.Tasks.Task<System.Guid> ScheduleContactAsync(System.Guid campaignId, Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact, System.DateTime dateTime) {
            return base.Channel.ScheduleContactAsync(campaignId, contact, dateTime);
        }
        
        public System.Guid MakeCall(Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact) {
            return base.Channel.MakeCall(contact);
        }
        
        public System.Threading.Tasks.Task<System.Guid> MakeCallAsync(Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact) {
            return base.Channel.MakeCallAsync(contact);
        }
        
        public System.Guid ScheduleCall(Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact, System.DateTime whenToMakeCall) {
            return base.Channel.ScheduleCall(contact, whenToMakeCall);
        }
        
        public System.Threading.Tasks.Task<System.Guid> ScheduleCallAsync(Esendex.Voice.Sdk.Esendex.VoiceService.Contact contact, System.DateTime whenToMakeCall) {
            return base.Channel.ScheduleCallAsync(contact, whenToMakeCall);
        }
        
        public Esendex.Voice.Sdk.Esendex.VoiceService.Callflow[] GetCallflows() {
            return base.Channel.GetCallflows();
        }
        
        public System.Threading.Tasks.Task<Esendex.Voice.Sdk.Esendex.VoiceService.Callflow[]> GetCallflowsAsync() {
            return base.Channel.GetCallflowsAsync();
        }
    }
}
